### ISSUE TITLE
Segmentation fault when fitting trees using v0.2.6 and v0.2.5

### ISSUE THREAD

**Issue by TimCargan** [tensorflow/decision-forests#113] opened 2022-06-06 14:37 UTC
I get a seg fault when I try and fit trees using TF 2.9.0 and TFDF 0.2.5 or TF 2.9.1 and TFDF 0.2.6. However it works fine with TF 2.8.2 and TFDF 0.2.4. This seems to be a local issue as I am unable to recreate it in colab. I am running in a clean conda environment with Python 3.9

My test code:
```python
import tensorflow as tf
import tensorflow_decision_forests as tfdf

d = tf.data.Dataset.range(6_000)
d = d.map(lambda x: ({"f1": x, "f2": tf.math.cos(tf.cast(x, tf.float32))}, 1))
d = d.batch(1024, drop_remainder=True)

m = tfdf.keras.GradientBoostedTreesModel(task=tfdf.keras.Task.REGRESSION, verbose=2,  num_trees=1, num_threads=1)
m.fit(x=d)
print(m.summary())
```

Here are the logs

```
2022-06-06 15:14:49.006237: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr2/local/cuda-11.2/extras/CUPTI/lib64:/usr2/local/cudnn/cudnn-11.0to2-v8.1.1.33/lib64:/usr2/local/cuda-11.2/lib64:/usr2/lib
2022-06-06 15:14:49.006284: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-06-06 15:14:49.006321: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (xavier): /proc/driver/nvidia/version does not exist
2022-06-06 15:14:49.006701: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Use /tmp/tmpgv4x8q20 as temporary training directory
Reading training dataset...
Training tensor examples:
Features: {'f1': <tf.Tensor 'data:0' shape=(1024,) dtype=int64>, 'f2': <tf.Tensor 'data_1:0' shape=(1024,) dtype=float32>}
Label: Tensor("data_2:0", shape=(1024,), dtype=int32)
Weights: None
Normalized tensor features:
 {'f1': SemanticTensor(semantic=<Semantic.NUMERICAL: 1>, tensor=<tf.Tensor 'Cast:0' shape=(1024,) dtype=float32>), 'f2': SemanticTensor(semantic=<Semantic.NUMERICAL: 1>, tensor=<tf.Tensor 'data_1:0' shape=(1024,) dtype=float32>)}
Training dataset read in 0:00:04.004277. Found 5120 examples.
Training model...
[INFO kernel.cc:809] Start Yggdrasil model training
[INFO kernel.cc:810] Collect training examples
[INFO kernel.cc:418] Number of batches: 5
[INFO kernel.cc:419] Number of examples: 5120
[INFO kernel.cc:832] Training dataset:
Number of records: 5120
Number of columns: 3

Number of columns by type:
	NUMERICAL: 2 (66.6667%)
	CATEGORICAL: 1 (33.3333%)

Columns:

NUMERICAL: 2 (66.6667%)
	0: "f1" NUMERICAL mean:2559.5 min:0 max:5119 sd:1478.02
	1: "f2" NUMERICAL mean:-9.83965e-05 min:-1 max:1 sd:0.70712

CATEGORICAL: 1 (33.3333%)
	2: "__LABEL" CATEGORICAL integerized vocab-size:3 no-ood-item

Terminology:
	nas: Number of non-available (i.e. missing) values.
	ood: Out of dictionary.
	manually-defined: Attribute which type is manually defined by the user i.e. the type was not automatically inferred.
	tokenized: The attribute value is obtained through tokenization.
	has-dict: The attribute is attached to a string dictionary e.g. a categorical attribute stored as a string.
	vocab-size: Number of unique values.

[INFO kernel.cc:878] Configure learner
[WARNING gradient_boosted_trees.cc:1663] Subsample hyperparameter given but sampling method does not match.
[WARNING gradient_boosted_trees.cc:1676] GOSS alpha hyperparameter given but GOSS is disabled.
[WARNING gradient_boosted_trees.cc:1685] GOSS beta hyperparameter given but GOSS is disabled.
[WARNING gradient_boosted_trees.cc:1697] SelGB ratio hyperparameter given but SelGB is disabled.
[INFO kernel.cc:908] Training config:
learner: "GRADIENT_BOOSTED_TREES"
features: "f1"
features: "f2"
label: "__LABEL"
task: CLASSIFICATION
random_seed: 123456
metadata {
  framework: "TF Keras"
}
[yggdrasil_decision_forests.model.gradient_boosted_trees.proto.gradient_boosted_trees_config] {
  num_trees: 1
  decision_tree {
    max_depth: 6
    min_examples: 5
    in_split_min_examples_check: true
    keep_non_leaf_label_distribution: true
    num_candidate_attributes: -1
    missing_value_policy: GLOBAL_IMPUTATION
    allow_na_conditions: false
    categorical_set_greedy_forward {
      sampling: 0.1
      max_num_items: -1
      min_item_frequency: 1
    }
    growing_strategy_local {
    }
    categorical {
      cart {
      }
    }
    axis_aligned_split {
    }
    internal {
      sorting_strategy: PRESORTED
    }
    uplift {
      min_examples_in_treatment: 5
      split_score: KULLBACK_LEIBLER
    }
  }
  shrinkage: 0.1
  loss: DEFAULT
  validation_set_ratio: 0.1
  validation_interval_in_trees: 1
  early_stopping: VALIDATION_LOSS_INCREASE
  early_stopping_num_trees_look_ahead: 30
  l2_regularization: 0
  lambda_loss: 1
  mart {
  }
  adapt_subsample_for_maximum_training_duration: false
  l1_regularization: 0
  use_hessian_gain: false
  l2_regularization_categorical: 1
  apply_link_function: true
  compute_permutation_variable_importance: false
  binary_focal_loss_options {
    misprediction_exponent: 2
    positive_sample_coefficient: 0.5
  }
}

[INFO kernel.cc:911] Deployment config:
num_threads: 1

[INFO kernel.cc:940] Train model
[INFO gradient_boosted_trees.cc:405] Default loss set to BINOMIAL_LOG_LIKELIHOOD
[INFO gradient_boosted_trees.cc:1004] Training gradient boosted tree on 5120 example(s) and 2 feature(s).
[INFO gradient_boosted_trees.cc:1047] 4619 examples used for training and 501 examples used for validation
[INFO gradient_boosted_trees.cc:1430] 	num-trees:1 train-loss:inf train-accuracy:1.000000 valid-loss:inf valid-accuracy:1.000000
[INFO gradient_boosted_trees.cc:230] Truncates the model to 1 tree(s) i.e. 1  iteration(s).
[INFO gradient_boosted_trees.cc:264] Final model num-trees:1 valid-loss:inf valid-accuracy:1.000000
[INFO kernel.cc:957] Export model in log directory: /tmp/tmpgv4x8q20 with prefix e7917500e6194380
[1]    22965 segmentation fault  python tftree.py
```

**Comment by rstz** [comment] 2022-06-07 07:48
Hi Tim,
I wasn't able to reproduce this on a fresh conda environment with Python 3.9.12 and TF 2.9.1 and TFDF 0.2.6. Could you please give more details on how to reproduce this error (maybe try reproducing on a different machine)?

**Comment by rstz** [comment] 2022-06-09 13:03
Thank you for providing an update! I'm going ahead and close this bug since we're unlikely to add support for CentOS 7.9, but feel free to open issues if you need additional support.

**Closed by rstz** 2022-06-09 13:03 UTC
